development:
  adapter: postgresql
  encoding: unicode
  database: database_development
  pool: 2
test:
  adapter: postgresql
  encoding: unicode
  databaes: database_test
  pool: 3
production: 
  url: <%= ENV['DATABASE_URL'] %>
  databaes: database_production
  pool: 5